apiVersion: v1
kind: ConfigMap
metadata:
  name: blogcommentsms-config
  namespace: blog-application
data:
  FLASK_APP: app.py
  FLASK_ENV: production
  DATABASE_URL: postgresql://username:password@hostname:5432/dbname
